"""create jobs tables

Revision ID: 5d88529d794b
Revises: 
Create Date: 2026-08-04 12:40:14.607773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d88529d794b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('workspace', sa.Text(), nullable=False),
    sa.Column('apply_nlp_filter', sa.Boolean(), nullable=False),
    sa.Column('max_chunks', sa.Integer(), nullable=False),
    sa.Column('max_chunk_tokens', sa.Integer(), nullable=False),
    sa.Column('max_paragraphs_per_chunk', sa.Integer(), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('max_batch_tokens', sa.Integer(), nullable=False),
    sa.Column('total_paragraphs', sa.Integer(), nullable=False),
    sa.Column('total_chunks_raw', sa.Integer(), nullable=False),
    sa.Column('filtered_out_chunks', sa.Integer(), nullable=False),
    sa.Column('total_chunks_available', sa.Integer(), nullable=False),
    sa.Column('total_chunks_to_process', sa.Integer(), nullable=False),
    sa.Column('completed_chunks', sa.Integer(), nullable=False),
    sa.Column('current_chunk', sa.Integer(), nullable=True),
    sa.Column('estimated_time_seconds', sa.Integer(), nullable=False),
    sa.Column('total_characters', sa.Integer(), nullable=False),
    sa.Column('total_relationships', sa.Integer(), nullable=False),
    sa.Column('total_sentiments', sa.Integer(), nullable=False),
    sa.Column('pause_requested', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('artifacts_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_session_id'), 'jobs', ['session_id'], unique=False)
    op.create_index(op.f('ix_jobs_state'), 'jobs', ['state'], unique=False)
    op.create_index(op.f('ix_jobs_updated_at'), 'jobs', ['updated_at'], unique=False)
    op.create_table('job_artifacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('compression', sa.String(length=32), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('compressed_size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'name', name='uq_job_artifacts_job_id_name')
    )
    op.create_index(op.f('ix_job_artifacts_job_id'), 'job_artifacts', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_artifacts_job_id'), table_name='job_artifacts')
    op.drop_table('job_artifacts')
    op.drop_index(op.f('ix_jobs_updated_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_state'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_session_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
